using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.AI;

public class EnemyMovement : MonoBehaviour
{
    private NavMeshAgent agent;
    private Transform playerTransform;


    void Start()
    {

        agent = GetComponent<NavMeshAgent>();


        GameObject player = GameObject.FindGameObjectWithTag("Player");
        if (player != null)
        {
            playerTransform = player.transform;
        }
    }

    void Update()
    {
        if(playerTransform != null)
        {
            agent.SetDestination(playerTransform.position);
        }
    }
}
